server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /fhir/ {
        proxy_pass http://hapi-fhir:8080/fhir/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /validate-sidecar {
        proxy_pass http://validator-service:3500/validate;
        proxy_set_header Host $host;
        proxy_read_timeout 300s;
        client_max_body_size 20m;
    }
    location / { try_files $uri $uri/ /index.html; }
}
