// ╭─────────────────────────────────────────────────────────────────────────────╮
// │  Shoulder Registry Surgery (SDC, complete template extraction)
// │  GENERATED by tools/generate-template-questionnaires.py — do not hand-edit. │
// ╰─────────────────────────────────────────────────────────────────────────────╯
//
// The whole submission, written out once as a contained Bundle. Template
// extraction reads nothing from the profiles, so every fixed code, category,
// unit and status here is stated literally; the structure and those fixed values
// are copied from a conformant example so the two cannot drift by hand.
//
// A leaf a clinician answers carries a templateExtractValue expression, and an
// expression yielding nothing removes its element. An entry that is optional
// carries a templateExtractContext instead, so leaving its question unanswered
// removes the entry outright.
//
// FHIRPath context is the QuestionnaireResponse, per templateExtractBundle
// sitting at the Questionnaire root.

Alias: $TEV = http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-templateExtractValue
Alias: $TECTX = http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-templateExtractContext
Alias: $ALLOC = http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-extractAllocateId
Alias: $BUNDLE = http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-templateExtractBundle
Alias: $CALC = http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-calculatedExpression
Alias: $INITIAL = http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression
Alias: $POPCTX = http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemPopulationContext

Instance: shoulder-surgery-full-template
InstanceOf: Questionnaire
Usage: #definition
Title: "Shoulder Registry Surgery (SDC, complete template extraction)"
Description: """
The complete surgical submission, extracted from a contained Bundle template.
Produces a Bundle labelled with the profile it claims, carrying the resources
the example it was generated from contains. That is a subset of what the profile
allows, not all of it.
"""
* meta.profile = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-extr-template"
* url = "https://maxpurk.github.io/shoulder-on-fhir/Questionnaire/shoulder-surgery-full-template"
* name = "ShoulderSurgeryFullTemplate"
* version = "0.1.0"
* status = #draft
* subjectType = #Patient
// The standard sanctions the two extraction mechanisms side by side only where
// one form is derived from the other, so the pairing is stated, not implied.
* derivedFrom = "https://maxpurk.github.io/shoulder-on-fhir/Questionnaire/shoulder-surgery"
// sdc-2: the version SUSHI stamps requires an accompanying versionAlgorithm.
* extension[0].url = "http://hl7.org/fhir/StructureDefinition/artifact-versionAlgorithm"
* extension[0].valueCoding = http://hl7.org/fhir/version-algorithm#semver

// what the form asks to be handed when it is launched
* extension[1].url = "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-launchContext"
* extension[1].extension[0].url = "name"
* extension[1].extension[0].valueCoding = http://hl7.org/fhir/uv/sdc/CodeSystem/launchContext#patient "Patient"
* extension[1].extension[1].url = "type"
* extension[1].extension[1].valueCode = #Patient
* extension[1].extension[2].url = "description"
* extension[1].extension[2].valueString = "The patient this submission is about."


// ── the uuids the entries reference each other by ────────────────────────────
* extension[2].url = $ALLOC
* extension[2].valueString = "encounterId"
* extension[3].url = $ALLOC
* extension[3].valueString = "procedure1"
* extension[4].url = $ALLOC
* extension[4].valueString = "procedure2"
* extension[5].url = $ALLOC
* extension[5].valueString = "ProcedureApproach1"
* extension[6].url = $ALLOC
* extension[6].valueString = "ReconstructionExtent1"
* extension[7].url = $ALLOC
* extension[7].valueString = "FixationTechnique1"
* extension[8].url = $ALLOC
* extension[8].valueString = "IntraopTearSize1"
* extension[9].url = $ALLOC
* extension[9].valueString = "IntraopTearSizeClassification1"
* extension[10].url = $ALLOC
* extension[10].valueString = "carePlanId"
* extension[11].url = $BUNDLE
* extension[11].valueReference.reference = "#submissionBundle"

// ╭──────────────────────────── the template ─────────────────────────────────╮
* contained[0].resourceType = "Bundle"
* contained[0].id = "submissionBundle"
// the template is only a Bundle; extraction labels the result
* contained[0].meta.profile[0] = "http://hl7.org/fhir/StructureDefinition/Bundle"
* contained[0].meta.profile[0].extension[0].url = $TEV
* contained[0].meta.profile[0].extension[0].valueString = "'https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/rotator-cuff-surgery-bundle'"
* contained[0].type = #transaction

// ---- entry 0: Encounter (shoulder-encounter) ----
* contained[0].entry[0].fullUrl = "urn:uuid:00000000-0000-4000-8000-000000000000"
* contained[0].entry[0].fullUrl.extension[0].url = $TEV
* contained[0].entry[0].fullUrl.extension[0].valueString = "%encounterId"
* contained[0].entry[0].resource.resourceType = "Encounter"
* contained[0].entry[0].resource.meta.profile[0] = "https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/shoulder-encounter"
* contained[0].entry[0].resource.status = #finished
* contained[0].entry[0].resource.class.system = "http://terminology.hl7.org/CodeSystem/v3-ActCode"
* contained[0].entry[0].resource.class.code = #IMP
* contained[0].entry[0].resource.class.display = "inpatient encounter"
* contained[0].entry[0].resource.type[0].coding[0].system = "http://snomed.info/sct"
* contained[0].entry[0].resource.type[0].coding[0].code = #308335008
* contained[0].entry[0].resource.type[0].coding[0].display = "Patient encounter procedure"
* contained[0].entry[0].resource.subject.reference = "Patient/AnnaMueller"
* contained[0].entry[0].resource.subject.reference.extension[0].url = $TEV
* contained[0].entry[0].resource.subject.reference.extension[0].valueString = "'Patient/' + %resource.repeat(item).where(linkId='context.patientId').answer.value"
* contained[0].entry[0].resource.period.start = "2024-04-15T09:00:00+02:00"
* contained[0].entry[0].resource.period.start.extension[0].url = $TEV
* contained[0].entry[0].resource.period.start.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value"
* contained[0].entry[0].resource.period.end = "2024-04-15T10:35:00+02:00"
* contained[0].entry[0].resource.period.end.extension[0].url = $TEV
* contained[0].entry[0].resource.period.end.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.endDate').answer.value"
* contained[0].entry[0].resource.reasonReference[0].reference = "Condition/AnnaRotatorCuffTear"
* contained[0].entry[0].resource.reasonReference[0].reference.extension[0].url = $TEV
* contained[0].entry[0].resource.reasonReference[0].reference.extension[0].valueString = "'Condition/' + %resource.repeat(item).where(linkId='context.conditionId').answer.value"
* contained[0].entry[0].request.method = #POST
* contained[0].entry[0].request.url = "Encounter"

// ---- entry 1: Procedure (rotator-cuff-procedure) ----
* contained[0].entry[1].fullUrl = "urn:uuid:00000000-0000-4000-8000-000000000001"
* contained[0].entry[1].fullUrl.extension[0].url = $TEV
* contained[0].entry[1].fullUrl.extension[0].valueString = "%procedure1"
* contained[0].entry[1].resource.resourceType = "Procedure"
* contained[0].entry[1].resource.meta.profile[0] = "https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/rotator-cuff-procedure"
* contained[0].entry[1].resource.meta.profile[1] = "http://hl7.org/fhir/uv/ips/StructureDefinition/Procedure-uv-ips"
* contained[0].entry[1].resource.status = #completed
* contained[0].entry[1].resource.category.coding[0].system = "http://snomed.info/sct"
* contained[0].entry[1].resource.category.coding[0].code = #387713003
* contained[0].entry[1].resource.category.coding[0].display = "Surgical procedure"
* contained[0].entry[1].resource.code.coding[0].system = "http://snomed.info/sct"
* contained[0].entry[1].resource.code.coding[0].code = #699120002
* contained[0].entry[1].resource.code.coding[0].display = "Arthroscopic repair of rotator cuff"
* contained[0].entry[1].resource.code.coding[0].extension[0].url = $TEV
* contained[0].entry[1].resource.code.coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='proc.type').answer.value"
* contained[0].entry[1].resource.subject.reference = "Patient/AnnaMueller"
* contained[0].entry[1].resource.subject.reference.extension[0].url = $TEV
* contained[0].entry[1].resource.subject.reference.extension[0].valueString = "'Patient/' + %resource.repeat(item).where(linkId='context.patientId').answer.value"
* contained[0].entry[1].resource.performedPeriod.start = "2024-04-15T09:00:00+02:00"
* contained[0].entry[1].resource.performedPeriod.start.extension[0].url = $TEV
* contained[0].entry[1].resource.performedPeriod.start.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value"
* contained[0].entry[1].resource.performedPeriod.end = "2024-04-15T10:35:00+02:00"
* contained[0].entry[1].resource.performedPeriod.end.extension[0].url = $TEV
* contained[0].entry[1].resource.performedPeriod.end.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.endDate').answer.value"
* contained[0].entry[1].resource.bodySite[0].coding[0].system = "http://snomed.info/sct"
* contained[0].entry[1].resource.bodySite[0].coding[0].code = #91774008
* contained[0].entry[1].resource.bodySite[0].coding[0].display = "Structure of right shoulder region"
* contained[0].entry[1].resource.bodySite[0].coding[0].extension[0].url = $TEV
* contained[0].entry[1].resource.bodySite[0].coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='cond.laterality').answer.value"
* contained[0].entry[1].resource.reasonReference[0].reference = "Condition/AnnaRotatorCuffTear"
* contained[0].entry[1].resource.reasonReference[0].reference.extension[0].url = $TEV
* contained[0].entry[1].resource.reasonReference[0].reference.extension[0].valueString = "'Condition/' + %resource.repeat(item).where(linkId='context.conditionId').answer.value"
* contained[0].entry[1].resource.outcome.coding[0].system = "http://snomed.info/sct"
* contained[0].entry[1].resource.outcome.coding[0].code = #385669000
* contained[0].entry[1].resource.outcome.coding[0].display = "Successful"
* contained[0].entry[1].resource.encounter.reference = "urn:uuid:00000000-0000-4000-8000-000000000000"
* contained[0].entry[1].resource.encounter.reference.extension[0].url = $TEV
* contained[0].entry[1].resource.encounter.reference.extension[0].valueString = "%encounterId"
* contained[0].entry[1].resource.performer[0].actor.display = "Dr. med. Sabine Hoffmann"
* contained[0].entry[1].request.method = #POST
* contained[0].entry[1].request.url = "Procedure"

// ---- entry 2: Procedure (rotator-cuff-procedure) ----
* contained[0].entry[2].extension[0].url = $TECTX
* contained[0].entry[2].extension[0].valueString = "%resource.repeat(item).where(linkId='proc.type.2').answer.value"
* contained[0].entry[2].fullUrl = "urn:uuid:00000000-0000-4000-8000-000000000002"
* contained[0].entry[2].fullUrl.extension[0].url = $TEV
* contained[0].entry[2].fullUrl.extension[0].valueString = "%procedure2"
* contained[0].entry[2].resource.resourceType = "Procedure"
* contained[0].entry[2].resource.meta.profile[0] = "https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/rotator-cuff-procedure"
* contained[0].entry[2].resource.meta.profile[1] = "http://hl7.org/fhir/uv/ips/StructureDefinition/Procedure-uv-ips"
* contained[0].entry[2].resource.status = #completed
* contained[0].entry[2].resource.category.coding[0].system = "http://snomed.info/sct"
* contained[0].entry[2].resource.category.coding[0].code = #387713003
* contained[0].entry[2].resource.category.coding[0].display = "Surgical procedure"
* contained[0].entry[2].resource.code.coding[0].system = "http://snomed.info/sct"
* contained[0].entry[2].resource.code.coding[0].code = #734057006
* contained[0].entry[2].resource.code.coding[0].display = "Excision of distal clavicle"
* contained[0].entry[2].resource.code.coding[0].extension[0].url = $TEV
* contained[0].entry[2].resource.code.coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='proc.type.2').answer.value"
* contained[0].entry[2].resource.subject.reference = "Patient/AnnaMueller"
* contained[0].entry[2].resource.subject.reference.extension[0].url = $TEV
* contained[0].entry[2].resource.subject.reference.extension[0].valueString = "'Patient/' + %resource.repeat(item).where(linkId='context.patientId').answer.value"
* contained[0].entry[2].resource.performedPeriod.start = "2024-04-15T09:00:00+02:00"
* contained[0].entry[2].resource.performedPeriod.start.extension[0].url = $TEV
* contained[0].entry[2].resource.performedPeriod.start.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value"
* contained[0].entry[2].resource.performedPeriod.end = "2024-04-15T10:35:00+02:00"
* contained[0].entry[2].resource.performedPeriod.end.extension[0].url = $TEV
* contained[0].entry[2].resource.performedPeriod.end.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.endDate').answer.value"
* contained[0].entry[2].resource.bodySite[0].coding[0].system = "http://snomed.info/sct"
* contained[0].entry[2].resource.bodySite[0].coding[0].code = #91774008
* contained[0].entry[2].resource.bodySite[0].coding[0].display = "Structure of right shoulder region"
* contained[0].entry[2].resource.bodySite[0].coding[0].extension[0].url = $TEV
* contained[0].entry[2].resource.bodySite[0].coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='cond.laterality').answer.value"
* contained[0].entry[2].resource.reasonReference[0].reference = "Condition/AnnaRotatorCuffTear"
* contained[0].entry[2].resource.reasonReference[0].reference.extension[0].url = $TEV
* contained[0].entry[2].resource.reasonReference[0].reference.extension[0].valueString = "'Condition/' + %resource.repeat(item).where(linkId='context.conditionId.2').answer.value"
* contained[0].entry[2].resource.outcome.coding[0].system = "http://snomed.info/sct"
* contained[0].entry[2].resource.outcome.coding[0].code = #385669000
* contained[0].entry[2].resource.outcome.coding[0].display = "Successful"
* contained[0].entry[2].resource.encounter.reference = "urn:uuid:00000000-0000-4000-8000-000000000000"
* contained[0].entry[2].resource.encounter.reference.extension[0].url = $TEV
* contained[0].entry[2].resource.encounter.reference.extension[0].valueString = "%encounterId"
* contained[0].entry[2].resource.partOf[0].reference = "urn:uuid:00000000-0000-4000-8000-000000000001"
* contained[0].entry[2].resource.partOf[0].reference.extension[0].url = $TEV
* contained[0].entry[2].resource.partOf[0].reference.extension[0].valueString = "%procedure1"
* contained[0].entry[2].resource.performer[0].actor.display = "Dr. med. Sabine Hoffmann"
* contained[0].entry[2].request.method = #POST
* contained[0].entry[2].request.url = "Procedure"

// ---- entry 3: Observation (procedure-approach-observation) ----
* contained[0].entry[3].extension[0].url = $TECTX
* contained[0].entry[3].extension[0].valueString = "%resource.repeat(item).where(linkId='obs.procedure-approach').answer.value"
* contained[0].entry[3].fullUrl = "urn:uuid:00000000-0000-4000-8000-000000000003"
* contained[0].entry[3].fullUrl.extension[0].url = $TEV
* contained[0].entry[3].fullUrl.extension[0].valueString = "%ProcedureApproach1"
* contained[0].entry[3].resource.resourceType = "Observation"
* contained[0].entry[3].resource.meta.profile[0] = "https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/procedure-approach-observation"
* contained[0].entry[3].resource.status = #final
* contained[0].entry[3].resource.category[0].coding[0].system = "http://terminology.hl7.org/CodeSystem/observation-category"
* contained[0].entry[3].resource.category[0].coding[0].code = #procedure
* contained[0].entry[3].resource.category[0].coding[0].display = "Procedure"
* contained[0].entry[3].resource.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/shoulder-observation"
* contained[0].entry[3].resource.code.coding[0].code = #procedure-approach
* contained[0].entry[3].resource.code.coding[0].display = "Procedure Approach"
* contained[0].entry[3].resource.subject.reference = "Patient/AnnaMueller"
* contained[0].entry[3].resource.subject.reference.extension[0].url = $TEV
* contained[0].entry[3].resource.subject.reference.extension[0].valueString = "'Patient/' + %resource.repeat(item).where(linkId='context.patientId').answer.value"
* contained[0].entry[3].resource.effectiveDateTime = "2024-04-15T09:00:00+02:00"
* contained[0].entry[3].resource.effectiveDateTime.extension[0].url = $TEV
* contained[0].entry[3].resource.effectiveDateTime.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value"
* contained[0].entry[3].resource.valueCodeableConcept.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/procedure-approach"
* contained[0].entry[3].resource.valueCodeableConcept.coding[0].code = #arthroscopic
* contained[0].entry[3].resource.valueCodeableConcept.coding[0].display = "Arthroscopic"
* contained[0].entry[3].resource.valueCodeableConcept.coding[0].extension[0].url = $TEV
* contained[0].entry[3].resource.valueCodeableConcept.coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='obs.procedure-approach').answer.value"
* contained[0].entry[3].resource.encounter.reference = "urn:uuid:00000000-0000-4000-8000-000000000000"
* contained[0].entry[3].resource.encounter.reference.extension[0].url = $TEV
* contained[0].entry[3].resource.encounter.reference.extension[0].valueString = "%encounterId"
* contained[0].entry[3].resource.partOf[0].reference = "urn:uuid:00000000-0000-4000-8000-000000000001"
* contained[0].entry[3].resource.partOf[0].reference.extension[0].url = $TEV
* contained[0].entry[3].resource.partOf[0].reference.extension[0].valueString = "%procedure1"
* contained[0].entry[3].request.method = #POST
* contained[0].entry[3].request.url = "Observation"

// ---- entry 4: Observation (reconstruction-extent-observation) ----
* contained[0].entry[4].extension[0].url = $TECTX
* contained[0].entry[4].extension[0].valueString = "%resource.repeat(item).where(linkId='obs.reconstruction-extent').answer.value"
* contained[0].entry[4].fullUrl = "urn:uuid:00000000-0000-4000-8000-000000000004"
* contained[0].entry[4].fullUrl.extension[0].url = $TEV
* contained[0].entry[4].fullUrl.extension[0].valueString = "%ReconstructionExtent1"
* contained[0].entry[4].resource.resourceType = "Observation"
* contained[0].entry[4].resource.meta.profile[0] = "https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/reconstruction-extent-observation"
* contained[0].entry[4].resource.status = #final
* contained[0].entry[4].resource.category[0].coding[0].system = "http://terminology.hl7.org/CodeSystem/observation-category"
* contained[0].entry[4].resource.category[0].coding[0].code = #procedure
* contained[0].entry[4].resource.category[0].coding[0].display = "Procedure"
* contained[0].entry[4].resource.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/shoulder-observation"
* contained[0].entry[4].resource.code.coding[0].code = #reconstruction-extent
* contained[0].entry[4].resource.code.coding[0].display = "Reconstruction Extent"
* contained[0].entry[4].resource.subject.reference = "Patient/AnnaMueller"
* contained[0].entry[4].resource.subject.reference.extension[0].url = $TEV
* contained[0].entry[4].resource.subject.reference.extension[0].valueString = "'Patient/' + %resource.repeat(item).where(linkId='context.patientId').answer.value"
* contained[0].entry[4].resource.effectiveDateTime = "2024-04-15T09:00:00+02:00"
* contained[0].entry[4].resource.effectiveDateTime.extension[0].url = $TEV
* contained[0].entry[4].resource.effectiveDateTime.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value"
* contained[0].entry[4].resource.valueCodeableConcept.coding[0].system = "http://snomed.info/sct"
* contained[0].entry[4].resource.valueCodeableConcept.coding[0].code = #304384006
* contained[0].entry[4].resource.valueCodeableConcept.coding[0].display = "Complete repair of rotator cuff"
* contained[0].entry[4].resource.valueCodeableConcept.coding[0].extension[0].url = $TEV
* contained[0].entry[4].resource.valueCodeableConcept.coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='obs.reconstruction-extent').answer.value"
* contained[0].entry[4].resource.encounter.reference = "urn:uuid:00000000-0000-4000-8000-000000000000"
* contained[0].entry[4].resource.encounter.reference.extension[0].url = $TEV
* contained[0].entry[4].resource.encounter.reference.extension[0].valueString = "%encounterId"
* contained[0].entry[4].resource.partOf[0].reference = "urn:uuid:00000000-0000-4000-8000-000000000001"
* contained[0].entry[4].resource.partOf[0].reference.extension[0].url = $TEV
* contained[0].entry[4].resource.partOf[0].reference.extension[0].valueString = "%procedure1"
* contained[0].entry[4].request.method = #POST
* contained[0].entry[4].request.url = "Observation"

// ---- entry 5: Observation (fixation-technique-observation) ----
* contained[0].entry[5].extension[0].url = $TECTX
* contained[0].entry[5].extension[0].valueString = "%resource.repeat(item).where(linkId='obs.fixation-technique').answer.value"
* contained[0].entry[5].fullUrl = "urn:uuid:00000000-0000-4000-8000-000000000005"
* contained[0].entry[5].fullUrl.extension[0].url = $TEV
* contained[0].entry[5].fullUrl.extension[0].valueString = "%FixationTechnique1"
* contained[0].entry[5].resource.resourceType = "Observation"
* contained[0].entry[5].resource.meta.profile[0] = "https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/fixation-technique-observation"
* contained[0].entry[5].resource.status = #final
* contained[0].entry[5].resource.category[0].coding[0].system = "http://terminology.hl7.org/CodeSystem/observation-category"
* contained[0].entry[5].resource.category[0].coding[0].code = #procedure
* contained[0].entry[5].resource.category[0].coding[0].display = "Procedure"
* contained[0].entry[5].resource.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/shoulder-observation"
* contained[0].entry[5].resource.code.coding[0].code = #fixation-technique
* contained[0].entry[5].resource.code.coding[0].display = "Fixation Technique"
* contained[0].entry[5].resource.subject.reference = "Patient/AnnaMueller"
* contained[0].entry[5].resource.subject.reference.extension[0].url = $TEV
* contained[0].entry[5].resource.subject.reference.extension[0].valueString = "'Patient/' + %resource.repeat(item).where(linkId='context.patientId').answer.value"
* contained[0].entry[5].resource.effectiveDateTime = "2024-04-15T09:00:00+02:00"
* contained[0].entry[5].resource.effectiveDateTime.extension[0].url = $TEV
* contained[0].entry[5].resource.effectiveDateTime.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value"
* contained[0].entry[5].resource.valueCodeableConcept.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/fixation-technique"
* contained[0].entry[5].resource.valueCodeableConcept.coding[0].code = #single-row
* contained[0].entry[5].resource.valueCodeableConcept.coding[0].display = "Single-row fixation"
* contained[0].entry[5].resource.valueCodeableConcept.coding[0].extension[0].url = $TEV
* contained[0].entry[5].resource.valueCodeableConcept.coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='obs.fixation-technique').answer.value"
* contained[0].entry[5].resource.encounter.reference = "urn:uuid:00000000-0000-4000-8000-000000000000"
* contained[0].entry[5].resource.encounter.reference.extension[0].url = $TEV
* contained[0].entry[5].resource.encounter.reference.extension[0].valueString = "%encounterId"
* contained[0].entry[5].resource.partOf[0].reference = "urn:uuid:00000000-0000-4000-8000-000000000001"
* contained[0].entry[5].resource.partOf[0].reference.extension[0].url = $TEV
* contained[0].entry[5].resource.partOf[0].reference.extension[0].valueString = "%procedure1"
* contained[0].entry[5].request.method = #POST
* contained[0].entry[5].request.url = "Observation"

// ---- entry 6: Observation (intraop-tear-size-observation) ----
* contained[0].entry[6].extension[0].url = $TECTX
* contained[0].entry[6].extension[0].valueString = "%resource.repeat(item).where(linkId='obs.intraop-tear-size').answer.value"
* contained[0].entry[6].fullUrl = "urn:uuid:00000000-0000-4000-8000-000000000006"
* contained[0].entry[6].fullUrl.extension[0].url = $TEV
* contained[0].entry[6].fullUrl.extension[0].valueString = "%IntraopTearSize1"
* contained[0].entry[6].resource.resourceType = "Observation"
* contained[0].entry[6].resource.meta.profile[0] = "https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/intraop-tear-size-observation"
* contained[0].entry[6].resource.status = #final
* contained[0].entry[6].resource.category[0].coding[0].system = "http://terminology.hl7.org/CodeSystem/observation-category"
* contained[0].entry[6].resource.category[0].coding[0].code = #exam
* contained[0].entry[6].resource.category[0].coding[0].display = "Exam"
* contained[0].entry[6].resource.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/shoulder-observation"
* contained[0].entry[6].resource.code.coding[0].code = #tear-size
* contained[0].entry[6].resource.code.coding[0].display = "Tear Size"
* contained[0].entry[6].resource.subject.reference = "Patient/AnnaMueller"
* contained[0].entry[6].resource.subject.reference.extension[0].url = $TEV
* contained[0].entry[6].resource.subject.reference.extension[0].valueString = "'Patient/' + %resource.repeat(item).where(linkId='context.patientId').answer.value"
* contained[0].entry[6].resource.effectiveDateTime = "2024-04-15T09:45:00+02:00"
* contained[0].entry[6].resource.effectiveDateTime.extension[0].url = $TEV
* contained[0].entry[6].resource.effectiveDateTime.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value"
* contained[0].entry[6].resource.valueQuantity.value = 3.2
* contained[0].entry[6].resource.valueQuantity.value.extension[0].url = $TEV
* contained[0].entry[6].resource.valueQuantity.value.extension[0].valueString = "%resource.repeat(item).where(linkId='obs.intraop-tear-size').answer.value"
* contained[0].entry[6].resource.valueQuantity.unit = "centimetres"
* contained[0].entry[6].resource.valueQuantity.system = "http://unitsofmeasure.org"
* contained[0].entry[6].resource.valueQuantity.code = #cm
* contained[0].entry[6].resource.encounter.reference = "urn:uuid:00000000-0000-4000-8000-000000000000"
* contained[0].entry[6].resource.encounter.reference.extension[0].url = $TEV
* contained[0].entry[6].resource.encounter.reference.extension[0].valueString = "%encounterId"
* contained[0].entry[6].resource.bodySite.coding[0].system = "http://snomed.info/sct"
* contained[0].entry[6].resource.bodySite.coding[0].code = #91774008
* contained[0].entry[6].resource.bodySite.coding[0].display = "Structure of right shoulder region"
* contained[0].entry[6].resource.bodySite.coding[0].extension[0].url = $TEV
* contained[0].entry[6].resource.bodySite.coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='cond.laterality').answer.value"
* contained[0].entry[6].request.method = #POST
* contained[0].entry[6].request.url = "Observation"

// ---- entry 7: Observation (intraop-tear-size-classification-observation) ----
* contained[0].entry[7].extension[0].url = $TECTX
* contained[0].entry[7].extension[0].valueString = "%resource.repeat(item).where(linkId='obs.intraop-tear-size-classification').answer.value"
* contained[0].entry[7].fullUrl = "urn:uuid:00000000-0000-4000-8000-000000000007"
* contained[0].entry[7].fullUrl.extension[0].url = $TEV
* contained[0].entry[7].fullUrl.extension[0].valueString = "%IntraopTearSizeClassification1"
* contained[0].entry[7].resource.resourceType = "Observation"
* contained[0].entry[7].resource.meta.profile[0] = "https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/intraop-tear-size-classification-observation"
* contained[0].entry[7].resource.status = #final
* contained[0].entry[7].resource.category[0].coding[0].system = "http://terminology.hl7.org/CodeSystem/observation-category"
* contained[0].entry[7].resource.category[0].coding[0].code = #exam
* contained[0].entry[7].resource.category[0].coding[0].display = "Exam"
* contained[0].entry[7].resource.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/shoulder-observation"
* contained[0].entry[7].resource.code.coding[0].code = #tear-size-classification
* contained[0].entry[7].resource.code.coding[0].display = "Tear Size Classification (Cofield)"
* contained[0].entry[7].resource.subject.reference = "Patient/AnnaMueller"
* contained[0].entry[7].resource.subject.reference.extension[0].url = $TEV
* contained[0].entry[7].resource.subject.reference.extension[0].valueString = "'Patient/' + %resource.repeat(item).where(linkId='context.patientId').answer.value"
* contained[0].entry[7].resource.effectiveDateTime = "2024-04-15T09:45:00+02:00"
* contained[0].entry[7].resource.effectiveDateTime.extension[0].url = $TEV
* contained[0].entry[7].resource.effectiveDateTime.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value"
* contained[0].entry[7].resource.valueCodeableConcept.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/cofield-tear-size-classification"
* contained[0].entry[7].resource.valueCodeableConcept.coding[0].code = #large
* contained[0].entry[7].resource.valueCodeableConcept.coding[0].display = "Large tear (3–5 cm)"
* contained[0].entry[7].resource.valueCodeableConcept.coding[0].extension[0].url = $TEV
* contained[0].entry[7].resource.valueCodeableConcept.coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='obs.intraop-tear-size-classification').answer.value"
* contained[0].entry[7].resource.encounter.reference = "urn:uuid:00000000-0000-4000-8000-000000000000"
* contained[0].entry[7].resource.encounter.reference.extension[0].url = $TEV
* contained[0].entry[7].resource.encounter.reference.extension[0].valueString = "%encounterId"
* contained[0].entry[7].resource.bodySite.coding[0].system = "http://snomed.info/sct"
* contained[0].entry[7].resource.bodySite.coding[0].code = #91774008
* contained[0].entry[7].resource.bodySite.coding[0].display = "Structure of right shoulder region"
* contained[0].entry[7].resource.bodySite.coding[0].extension[0].url = $TEV
* contained[0].entry[7].resource.bodySite.coding[0].extension[0].valueString = "%resource.repeat(item).where(linkId='cond.laterality').answer.value"
* contained[0].entry[7].request.method = #POST
* contained[0].entry[7].request.url = "Observation"

// ---- entry 8: CarePlan (rotator-cuff-research-care-plan) ----
* contained[0].entry[8].fullUrl = "urn:uuid:00000000-0000-4000-8000-000000000008"
* contained[0].entry[8].fullUrl.extension[0].url = $TEV
* contained[0].entry[8].fullUrl.extension[0].valueString = "%carePlanId"
* contained[0].entry[8].resource.resourceType = "CarePlan"
* contained[0].entry[8].resource.meta.profile[0] = "https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/rotator-cuff-research-care-plan"
* contained[0].entry[8].resource.status = #active
* contained[0].entry[8].resource.intent = #plan
* contained[0].entry[8].resource.subject.reference = "Patient/AnnaMueller"
* contained[0].entry[8].resource.subject.reference.extension[0].url = $TEV
* contained[0].entry[8].resource.subject.reference.extension[0].valueString = "'Patient/' + %resource.repeat(item).where(linkId='context.patientId').answer.value"
* contained[0].entry[8].resource.period.start = "2024-04-15T09:00:00+02:00"
* contained[0].entry[8].resource.period.start.extension[0].url = $TEV
* contained[0].entry[8].resource.period.start.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value"
* contained[0].entry[8].resource.period.end = "2026-04-15T09:00:00+02:00"
* contained[0].entry[8].resource.period.end.extension[0].url = $TEV
* contained[0].entry[8].resource.period.end.extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value + 2 years"
* contained[0].entry[8].resource.activity[0].detail.status = #scheduled
* contained[0].entry[8].resource.activity[0].detail.scheduledTiming.event[0] = "2024-05-27T09:00:00+02:00"
* contained[0].entry[8].resource.activity[0].detail.scheduledTiming.event[0].extension[0].url = $TEV
* contained[0].entry[8].resource.activity[0].detail.scheduledTiming.event[0].extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value + 6 weeks"
* contained[0].entry[8].resource.activity[0].detail.description = "Q11 research follow-up — 6 wk post-surgery"
* contained[0].entry[8].resource.activity[0].detail.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/q11-timepoint"
* contained[0].entry[8].resource.activity[0].detail.code.coding[0].code = #6-weeks
* contained[0].entry[8].resource.activity[1].detail.status = #scheduled
* contained[0].entry[8].resource.activity[1].detail.scheduledTiming.event[0] = "2024-07-14T09:00:00+02:00"
* contained[0].entry[8].resource.activity[1].detail.scheduledTiming.event[0].extension[0].url = $TEV
* contained[0].entry[8].resource.activity[1].detail.scheduledTiming.event[0].extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value + 3 months"
* contained[0].entry[8].resource.activity[1].detail.description = "Q11 research follow-up — 3 mo post-surgery"
* contained[0].entry[8].resource.activity[1].detail.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/q11-timepoint"
* contained[0].entry[8].resource.activity[1].detail.code.coding[0].code = #3-months
* contained[0].entry[8].resource.activity[2].detail.status = #scheduled
* contained[0].entry[8].resource.activity[2].detail.scheduledTiming.event[0] = "2024-10-12T09:00:00+02:00"
* contained[0].entry[8].resource.activity[2].detail.scheduledTiming.event[0].extension[0].url = $TEV
* contained[0].entry[8].resource.activity[2].detail.scheduledTiming.event[0].extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value + 6 months"
* contained[0].entry[8].resource.activity[2].detail.description = "Q11 research follow-up — 6 mo post-surgery"
* contained[0].entry[8].resource.activity[2].detail.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/q11-timepoint"
* contained[0].entry[8].resource.activity[2].detail.code.coding[0].code = #6-months
* contained[0].entry[8].resource.activity[3].detail.status = #scheduled
* contained[0].entry[8].resource.activity[3].detail.scheduledTiming.event[0] = "2025-04-15T09:00:00+02:00"
* contained[0].entry[8].resource.activity[3].detail.scheduledTiming.event[0].extension[0].url = $TEV
* contained[0].entry[8].resource.activity[3].detail.scheduledTiming.event[0].extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value + 1 year"
* contained[0].entry[8].resource.activity[3].detail.description = "Q11 research follow-up — 12 mo post-surgery"
* contained[0].entry[8].resource.activity[3].detail.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/q11-timepoint"
* contained[0].entry[8].resource.activity[3].detail.code.coding[0].code = #1-year
* contained[0].entry[8].resource.activity[4].detail.status = #scheduled
* contained[0].entry[8].resource.activity[4].detail.scheduledTiming.event[0] = "2026-04-15T09:00:00+02:00"
* contained[0].entry[8].resource.activity[4].detail.scheduledTiming.event[0].extension[0].url = $TEV
* contained[0].entry[8].resource.activity[4].detail.scheduledTiming.event[0].extension[0].valueString = "%resource.repeat(item).where(linkId='encounter.date').answer.value + 2 years"
* contained[0].entry[8].resource.activity[4].detail.description = "Q11 research follow-up — 24 mo post-surgery"
* contained[0].entry[8].resource.activity[4].detail.code.coding[0].system = "https://maxpurk.github.io/shoulder-on-fhir/CodeSystem/q11-timepoint"
* contained[0].entry[8].resource.activity[4].detail.code.coding[0].code = #2-years
* contained[0].entry[8].request.method = #POST
* contained[0].entry[8].request.url = "CarePlan"

// ╭──────────────────────────── the form ─────────────────────────────────────╮

* item[0].linkId = "context"
* item[0].text = "Registered Patient"
* item[0].type = #group
* item[0].extension[0].url = $POPCTX
* item[0].extension[0].valueExpression.name = "rotatorCuffCondition"
* item[0].extension[0].valueExpression.language = #application/x-fhir-query
* item[0].extension[0].valueExpression.expression = "Condition?subject={{%patient.id}}&_profile=https://maxpurk.github.io/shoulder-on-fhir/StructureDefinition/rotator-cuff-condition"
* item[0].item[0].linkId = "context.conditionId"
* item[0].item[0].text = "Rotator Cuff Condition ID (from the registration)"
* item[0].item[0].type = #string
* item[0].item[0].required = true
* item[0].item[0].extension[0].url = $INITIAL
* item[0].item[0].extension[0].valueExpression.language = #text/fhirpath
* item[0].item[0].extension[0].valueExpression.expression = "%rotatorCuffCondition.id"
* item[0].item[1].linkId = "context.conditionId.2"
* item[0].item[1].text = "Shoulder Diagnosis Condition ID"
* item[0].item[1].type = #string
* item[0].item[2].linkId = "context.patientId"
* item[0].item[2].text = "Patient Resource ID (from the registration)"
* item[0].item[2].type = #string
* item[0].item[2].required = true
* item[0].item[2].extension[0].url = $INITIAL
* item[0].item[2].extension[0].valueExpression.language = #text/fhirpath
* item[0].item[2].extension[0].valueExpression.expression = "%patient.id"

* item[1].linkId = "encounter"
* item[1].text = "Visit"
* item[1].type = #group
* item[1].item[0].linkId = "encounter.date"
* item[1].item[0].text = "Visit / Incision Date and Time"
* item[1].item[0].type = #dateTime
* item[1].item[0].required = true
* item[1].item[1].linkId = "encounter.endDate"
* item[1].item[1].text = "Visit / Closure Date and Time"
* item[1].item[1].type = #dateTime
* item[1].item[1].required = true

* item[2].linkId = "cond"
* item[2].text = "Diagnoses"
* item[2].type = #group
* item[2].item[0].linkId = "cond.laterality"
* item[2].item[0].text = "Affected Side"
* item[2].item[0].type = #choice
* item[2].item[0].required = true
* item[2].item[0].answerValueSet = "https://maxpurk.github.io/shoulder-on-fhir/ValueSet/shoulder-laterality"

* item[3].linkId = "proc"
* item[3].text = "Procedures"
* item[3].type = #group
* item[3].item[0].linkId = "proc.type"
* item[3].item[0].text = "Procedure Type"
* item[3].item[0].type = #choice
* item[3].item[0].required = true
* item[3].item[0].answerValueSet = "https://maxpurk.github.io/shoulder-on-fhir/ValueSet/rotator-cuff-procedure-type"
* item[3].item[1].linkId = "proc.type.2"
* item[3].item[1].text = "Concomitant Procedure 1 (if performed)"
* item[3].item[1].type = #choice
* item[3].item[1].answerValueSet = "https://maxpurk.github.io/shoulder-on-fhir/ValueSet/rotator-cuff-procedure-type"

* item[4].linkId = "obs"
* item[4].text = "Clinical Assessment"
* item[4].type = #group
* item[4].item[0].linkId = "obs.intraop-tear-size"
* item[4].item[0].text = "Tear Size (centimetres)"
* item[4].item[0].type = #decimal
* item[4].item[1].linkId = "obs.intraop-tear-size-classification"
* item[4].item[1].text = "Tear Size Classification (Cofield)"
* item[4].item[1].type = #choice
* item[4].item[1].answerValueSet = "https://maxpurk.github.io/shoulder-on-fhir/ValueSet/cofield-tear-size-classification"
* item[4].item[2].linkId = "obs.procedure-approach"
* item[4].item[2].text = "Procedure Approach"
* item[4].item[2].type = #choice
* item[4].item[2].answerValueSet = "https://maxpurk.github.io/shoulder-on-fhir/ValueSet/procedure-approach"
* item[4].item[3].linkId = "obs.reconstruction-extent"
* item[4].item[3].text = "Reconstruction Extent"
* item[4].item[3].type = #choice
* item[4].item[3].answerValueSet = "https://maxpurk.github.io/shoulder-on-fhir/ValueSet/reconstruction-extent"
* item[4].item[4].linkId = "obs.fixation-technique"
* item[4].item[4].text = "Fixation Technique"
* item[4].item[4].type = #choice
* item[4].item[4].answerValueSet = "https://maxpurk.github.io/shoulder-on-fhir/ValueSet/fixation-technique"
